### ISSUE TITLE
Mastodon related info

### ISSUE THREAD

**Issue by ronguest** [microdotblog/help.micro.blog#10]
I'm not sure if this should be an enhancement to the ActivityPub help page or a separate help item. But for folks like me it would be nice to explicitly state that setting up the ActivityPub name means micro.blog posts will be sent to mastodon's federated timeline. Also, that to follow a mastodon user enter their name in the search field of Discover.

**Comment by m4sk1n** [comment]
Not just Mastodon, but also Pleroma, Misskey, Friendica (with 2018.12 update) etc.

**Comment by manton** [comment]
Great point, thank you. For now I'm going to add a note and screenshot about following Mastodon users directly to the ActivityPub help page, but I think splitting this out into separate help pages is going to be needed later.

**Comment by manton** [comment]
Updated the ActivityPub help page with screenshots and a mention of the federated timeline.
