### ISSUE TITLE
“First steps” article should mention filling in “About me” info

### ISSUE THREAD

**Issue by sardisson** [microdotblog/help.micro.blog#21]
Earlier this week, @jeanmacd [posted a reminder to new folks](https://micro.blog/macgenie/2583325) to fill in their About info to help them be discovered.

There should be a little blurb about that in the [First steps](https://help.micro.blog/2017/getting-started/) help article, too, with a bit of rationale—primarily discovery.

After some discussions within the community last fall, I wrote [an article](https://www.ardisson.org/afkar/2018/08/30/thinking-about-about-me/) going into more depth about things we thought would be useful to (optionally) include in one’s “About me” and the reasoning behind including them; we shouldn’t replicate the article on the help page, but a quick list of possible items to include would be good.

**Comment by sardisson** [comment]
Ron today [also suggested](https://micro.blog/Ron/2866401) that First Steps should mention filling in About me info:

> Shouldn't it go on the First Steps page, right after the Second section & before the Next section? We want them writing a bit about who they are before they start posting or even following others, right?

**Comment by manton** [comment]
This was updated recently to mention "about me". Thanks!
