### ISSUE TITLE
Add a note to the Pricing page about GitHub mirroring

### ISSUE THREAD

**Issue by simon-woods** [microdotblog/help.micro.blog#22]
Mirroring to GitHub Pages is currently listed as a feature for the Hosted subscription [on the Pricing page](http://help.micro.blog/2018/pricing/), despite the fact that mirroring currently isn't working and hasn't been for a while (as far as I can remember).

I wonder if for this specifically, and the Pricing page in general, it would be prudent to add a note whenever certain features have been inactive for a certain amount of time.

I think this kind of transparency would be only strengthen the value of the subscriptions since it would be 100% clear nothing is being hidden or lied about, even if it is unintentional.

**Comment by sardisson** [comment]
There is a disclaimer [now](https://github.com/microdotblog/help.micro.blog/commit/627f0576f19b0e3cdd95b48b228126ece403cd18) on the help page for the feature, but I agree the Pricing page should reference it.

**Comment by manton** [comment]
Agreed. I updated the pricing page recently and removed the GitHub mention. Thanks.
