### ISSUE TITLE
Micropub photo accessibility description parameter mp-photo-alt[]= not documented

### ISSUE THREAD

**Issue by sardisson** [microdotblog/help.micro.blog#24]
I can’t find the `mp-photo-alt[]=` Micropub parameter (used for passing an image’s `alt` text/accessibility description) documented on the Help site (I’d have expected it on the [Posting API](https://help.micro.blog/2017/api-posting/) page).

Nor, for that matter, can I find it mentioned on Manton’s blog; I don’t remember now where I read Manton introduce and provide an example of it, but I can’t believe it wasn’t on his blog somewhere.

I guess [this](https://indieweb.org/Micropub-brainstorming#Alternative_text_for_photos_in_form-encoded) is the only documentation for it, at least that I can find?

It really should be documented, as implemented on Micro.blog, with examples, on the Help site.

**Comment by manton** [comment]
Thanks! I've updated the documentation to include more about including a photo and alt text in a post.

There is still a lot that Micro.blog's API supports that isn't covered in the documentation. I think we need a longer guide that can be linked from this help page.

**Comment by sardisson** [comment]
Thanks, @manton 

> There is still a lot that Micro.blog's API supports that isn't covered in the documentation. I think we need a longer guide that can be linked from this help page.

That sounds like a good idea (today I noticed [this post](https://micro.blog/ChrisJWilson/3109677) you answered where Chris Wilson was asking about setting categories).
