### ISSUE TITLE
Profile photos needs updating

### ISSUE THREAD

**Issue by sardisson** [microdotblog/help.micro.blog#4]
Since at least the arrival of podcasting support, Gravatars are deprecated and @manton blogged suggesting everyone upload a profile picture directly: http://www.manton.org/2018/04/15/changed-the-default.html

The Profile photos page needs to be updated to reflect this: http://help.micro.blog/2015/profile-photos/

(Are Gravatars still supported at all?)

**Comment by manton** [comment]
Thanks @sardisson! Sorry I hadn't gotten to this yet. I just rewrote the profile photo help page to de-emphasize Gravatar support. Uploading a new image to Micro.blog is best, but we'll still support Gravatar as a fallback to make it easier to get started.
